version: 0.1.{build}

branches:
  only:
    - master

image:
  - Visual Studio 2019
  - macos
  - Ubuntu2004

stack: node 14

init:
  - git config --global core.autocrlf input
  - sh: |
      if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" == "Ubuntu2004" ]
      then
        sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
        sudo apt-get install snapd
        sudo snap install snapcraft --classic
        sudo apt-get install -y rpm
      fi

install:
  - git reset --hard HEAD
  - npm install node-sass@4.14.1
  - node --version
  - npm install

build_script:
  - npm run release

test: off
