name: Bug Report
description: Things don't work as intended
labels: "bug"

body:
  - type: checkboxes
    id: testing1
    attributes:
      label: I've already installed the latest developer version of Koodo Reader, this problem still exsits
      description: https://github.com/troyeguo/koodo-reader/releases/latest
      options:
        - label: "Yes"
          required: true

  - type: checkboxes
    id: testing2
    attributes:
      label: There are no similar issues on the issue list
      description: https://github.com/troyeguo/koodo-reader/issues
      options:
        - label: "Yes"
          required: true

  - type: checkboxes
    id: testing3
    attributes:
      label: I've already read the document, still can't solve it.
      description: https://troyeguo.notion.site/Koodo-Reader-Document-9c767af3d66c459db996bdd08a34c34b
      options:
        - label: "Yes"
          required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system or browser
      description: which OS you are using ?
      options:
        - Windows 10 and below
        - Windows 11
        - macOS 10 and below
        - macOS 11
        - macOS 12
        - Ubuntu
        - Other Linux distribution
        - Chrome/Edge
        - Firefox
        - IE
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: App Version
      placeholder: You can found app version in Setting->Version
    validations:
      required: true

  - type: textarea
    id: bug_detail
    attributes:
      label: Bug Detail
      placeholder: Please describe your problem in detail
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots (Optional)
      placeholder: Clicking on this box and drag your screenshots or videos here to upload them
    validations:
      required: false

  - type: textarea
    id: download
    attributes:
      label: Files (Optional)
      placeholder: 1. Compress your files into a zip file; 2. Clicking on this box; 3. Drag and drop here
    validations:
      required: false
