name: Feature Request
description: What feature do you think is missing in Koodo Reader
labels: "feature request"
body:
  - type: checkboxes
    id: testing1
    attributes:
      label: I've read Koodo Reader's roadmap, there is no similar feature.
      description: https://www.notion.so/troyeguo/d1c19a132932465bae1d89dd963c92ea?v=ca8aa69cf25849c18c92b92ba868663b
      options:
        - label: "Yes"
          required: true

  - type: checkboxes
    id: testing2
    attributes:
      label: This issue only requests one feature.
      options:
        - label: "Yes"
          required: true

  - type: textarea
    id: introduction
    attributes:
      label: Brief Introduction
      placeholder: Brief introduction to this feature
    validations:
      required: true

  - type: textarea
    id: detail
    attributes:
      label: Details
      placeholder: More details about this feature
    validations:
      required: true
