name: 问题反馈
description: 我在使用 Koodo Reader 时遇到了问题
labels: "bug"
body:
  - type: checkboxes
    id: testing1
    attributes:
      label: 我已经安装了最新开发版的 Koodo Reader，这个问题仍然存在
      description: https://github.com/troyeguo/koodo-reader/releases/latest
      options:
        - label: "Yes"
    validations:
      required: true

  - type: checkboxes
    id: testing2
    attributes:
      label: 我已经搜索了已有的 Issues列表，没有找到类似的issue
      options:
        - label: "Yes"
    validations:
      required: true

  - type: checkboxes
    id: testing3
    attributes:
      label: 我已经阅读了 Koodo Reader 的帮助文档，仍然无法解决
      description: https://www.notion.so/troyeguo/e9c4e5755d564b0db6340eeba6d9ece9?v=7c8fcbed9adf4592ada95cfd593868c9
      options:
        - label: "Yes"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: 操作系统
      options:
        - Windows
        - macOS
        - Linux
        - 网页版
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Koodo Reader 版本
      placeholder: 您可以在设置->版本号查看
    validations:
      required: true

  - type: textarea
    id: bug
    attributes:
      label: 我遇到的问题
      placeholder: 描述您遇到的问题以及如何复现该问题
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: 截图或录像(可选的)
      placeholder: 截图和录像会帮助开发者定位问题
    validations:
      required: false

  - type: textarea
    id: download
    attributes:
      label: 图书的下载链接(可选的)
      placeholder: 您遇到问题时正在阅读的图书
    validations:
      required: false
