blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/troyeguo/koodo-reader/discussions
    about: Looking for help or Starting a discussion about Koodo Reader
  - name: 提问与讨论
    url: https://github.com/troyeguo/koodo-reader/discussions
    about: 使用 Koodo Reader 时遇到了问题，或者想发起一个讨论
